# Generated by Django 3.2 on 2021-04-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='usuario',
            new_name='user',
        ),
    ]
